version: '3.0'
services:
  web:
    build:
      context: .
      dockerfile: ./Containers/Client.Dockerfile
    ports:
      - "8080:8080"
  server:
    build:
      context: .
      dockerfile: ./Containers/Server.Dockerfile
    ports:
      - "4000:4000"
  database:
    build:
      context: .
      dockerfile: ./Containers/Database.Dockerfile
    ports:
      - "1433:1433"
